### ISSUE TITLE
zero exit status when  wrong usage

### ISSUE THREAD

**Issue by PhilLAL** [tango-controls/tango_admin#1]
Hi Manu,
using tango_admin into shell scripts, I noticed in exceptional context that wrong usage returns exit status equal to 0 but it seems to me this should be non zero status. Am I wrong?
Regards

**Comment by bourtemb** [comment]
Hi @PhilLAL 
Thanks for the bug report.
I agree with you, we should change that.

**Comment by PhilLAL** [comment]
I am not sure a zero status is returned in all case, could someone confirm the value status?
Thank you.

**Comment by bourtemb** [comment]
Hi @PhilLAL, just look for all the lines with the keyword "return" in the source code:
https://github.com/tango-controls/tango_admin/blob/master/tango_admin.cpp

You will see there are many cases where a non-zero value is returned.

**Comment by PhilLAL** [comment]
Indeed, don't know why I did not find the call functions at first time. 
Since I was interested in possible return values I can get from tango_admin to use it for test, here is a list if it can help other users.

It seems tango_admin returns a 0 value when:
- it is launched without any parameter
- with help parameter
- a bad number of parameters 
- a bad option for ping-network
- test succeed

Otherwise, return values read by `echo $?` are 255.

**Comment by PhilLAL** [comment]
Sorry, I reopened the ticket since perhaps return values should be different whether the test succeed or if test is not even launched.

**Comment by PhilLAL** [comment]
If necessary, I found /usr/include/sysexits.h which lists some GNU/Linux error return values, I'm not sure how "standard" it is but I hope this can help.

**Comment by t-b** [comment]
@PhilLAL How about just returning 1 in all error cases for now. We can then later on, if needed, add specific return values, for specific error conditions.

**Comment by PhilLAL** [comment]
Hi @t-b, it would probably be better for test cases.
